name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
        - label: I have read the [documentation](https://github.com/Swartdraak/Docker-MCP#readme)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area does this feature request relate to?
      options:
        - Container Management
        - Image Operations
        - Network Management
        - Volume Management
        - System Operations
        - Remote Connections
        - Security/Authentication
        - Documentation
        - Testing
        - CLI/UX
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Use case 1: ...
        2. Use case 2: ...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: Show how you would use this feature (code examples, commands, etc.)
      render: javascript
      placeholder: |
        // Example of how this feature might be used
        const result = await dockerMcp.newFeature(...);
    validations:
      required: false

  - type: dropdown
    id: willing
    attributes:
      label: Willing to Contribute
      description: Would you be willing to contribute this feature?
      options:
        - "Yes, I can implement this"
        - "Yes, with guidance"
        - "No, but I can test it"
        - "No"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
    validations:
      required: false
